[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = ["corepack enable"]

[variables]
COREPACK_INTEGRITY_KEYS = ""
NODE_ENV = "development"

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["cd apps/backend && pnpm build && ls -la .medusa/server/public/admin/"]

[start]
cmd = "cd /app/apps/backend && NODE_ENV=production npx medusa start"
